# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Pytest and Linter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: 'pip'
        cache-dependency-path: |
          requirements.txt
          requirements-dev.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install development dependencies (e.g., flake8, pytest)
        # It's recommended to list these in a 'requirements-dev.txt' file
        # and include their versions for reproducible builds.
        if [ -f requirements-dev.txt ]; then
          echo "Installing dependencies from requirements-dev.txt"
          pip install -r requirements-dev.txt
        else
          echo "Warning: requirements-dev.txt not found. Installing flake8 and pytest directly."
          pip install flake8 pytest
        fi
        # Install main application dependencies
        if [ -f requirements.txt ]; then
          echo "Installing dependencies from requirements.txt"
          pip install -r requirements.txt
        fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
